name: "Generics, Traits, Lifetimes"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ./common_collections
      - Cargo.toml
      - Cargo.lock

jobs:
  check:
    name: "Check"
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install rust
        run: rustup default stable

      - name: compile
        run: cargo check -p common_collections
  build:
    name: "Build"
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install rust
        run: rustup default stable

      - name: compile
        run: cargo build -p common_collections
