name: "Hello World"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ./hello-world/**
      - Cargo.toml
      - Cargo.lock

jobs:
  build:
    name: "Build"
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install rust
        run: rustup default stable

      - name: compile
        run: cargo build -p hello-world
