name: Nix Shell

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.nix'
    branches:
      - main

jobs:
  validate:
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    name: "Validate"
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: install nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: validate
        run: nix-shell --pure --command "exit"
